### ISSUE TITLE
CLI ETA?

### ISSUE THREAD

**Issue by j2l** [Bogdan-Lyashenko/js-code-to-svg-flowchart#14]
Hey,

Thanks for this one!
I'd like to test on a React Native using CLI.
Is there an ETA?
Pasting in a code editor didn't work :(

**Comment by Bogdan-Lyashenko** [comment]
@j2l , hi, thanks.
Can you please show which code doesn't work? Or what error are you getting in dev-tools. Thanks.

**Comment by j2l** [comment]
Thanks for replying quickly!
First I tried to paste some react native code in a online editor (from Under the hood ReactJS) and svg wasn't produced, no error seen.

Then I tried CLI: npm i -g js2flowchart installed it but jsflowchart is a unknown command.

**Comment by Bogdan-Lyashenko** [comment]
Hey, it wasn’t implemented yet, that’s why it didn’t work like global install. I pushed a CLI feature yesterday, please update js2flowchart from npm and try again. Thanks. Let me know if still have issues.

**Comment by j2l** [comment]
Cool!

But it doesn't like some react native:
```
js2flowchart App.js
Error at parseCodeToAST: Unexpected token (51:8)
C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:18131
        throw e;
        ^

SyntaxError: Unexpected token (51:8)
    at Parser.pp$5.raise (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:13702:13)
    at Parser.pp.unexpected (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11009:8)
    at Parser.pp$1.parseClassProperty (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11819:50)
    at Parser.pp$1.parseClassBody (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11764:34)
    at Parser.pp$1.parseClass (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11654:8)
    at Parser.pp$1.parseExport (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11890:19)
    at Parser.pp$1.parseStatement (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11132:74)
    at Parser.pp$1.parseBlockBody (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11516:21)
    at Parser.pp$1.parseTopLevel (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:11026:8)
    at Parser.parse (C:\Users\pm\AppData\Roaming\npm\node_modules\js2flowchart\dist\js2flowchart.js:10921:17)
```

**Comment by Bogdan-Lyashenko** [comment]
@j2l, there is a code
```javascript
state = {
    appIsReady: false
  };
```
inside of class definition. It's not like es6 way of doing that and I use es6-only parser which doesn't like it  (it's not valid actually from that point of view), so it breaks there. So if you remove that 3 lines and try without it, you'll see it works fine.

**Comment by j2l** [comment]
Indeed :)
Fixed for me.
Cheers!
