### ISSUE TITLE
js2flowchart CLI doesn't work 

### ISSUE THREAD

**Issue by Os3r3um** [Bogdan-Lyashenko/js-code-to-svg-flowchart#15]
Hi, 

First, thank you for your work!

Secondly, I got a try and I do have some issue with making it running. 

This is how I test it.

- Got an Ubuntu 16.04 LTS.

- Installed yarn as this resource describes:

[(https://stackoverflow.com/questions/42606941/install-yarn-ubuntu-16-04-linux-mint-18-1) ]

- Got this JS file, masonry.min.js, as a test bed. [https://masonry.desandro.com/]

This is the error which I got:

```
js2flowchart masonry.min.js 
Error at buildFlowTreeFromAst[_constants.TOKEN_KEYS.CONSEQUENT,_constants.TOKEN_KEYS.ALTERNATE].includes is not a function
/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:7465
                throw e;
                ^

TypeError: [_constants.TOKEN_KEYS.CONSEQUENT,_constants.TOKEN_KEYS.ALTERNATE].includes is not a function
    at Object.singleTypeFilter [as ignore] (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:4266:77)
    at /usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:18165:33
    at /usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:18144:20
    at NodePath._call (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:29049:18)
    at NodePath.call (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:29021:17)
    at NodePath.visit (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:29078:12)
    at TraversalContext.visitQueue (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:30339:16)
    at TraversalContext.visitMultiple (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:30292:17)
    at TraversalContext.visit (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:30379:19)
    at Function.traverse.node (/usr/local/share/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:2646:17)
```
Any ideas why I'm getting this?

Thanks.

**Comment by Os3r3um** [comment]
Right. Thank you. Will have the nodejs updated to the latest and have you updated. will close the issue now and reopen it if that would be necessary. 

Thanks!
