### ISSUE TITLE
Error parsing react component

### ISSUE THREAD

**Issue by KBPratap** [Bogdan-Lyashenko/js-code-to-svg-flowchart#40]
When I tried to parse my first jsx, I got this error but I see no reference to `classProperties` in github documentation. Am I missing something?
```
Error at parseCodeToAST: This experimental syntax requires enabling the parser plugin: 'classProperties' (29:21)
<user-home>/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:40029
        throw e;
        ^

SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (29:21)
    at _class.raise (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:15623:15)
    at _class.expectPlugin (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:16913:18)
    at _class.parseClassProperty (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:19716:12)
    at _class.parseClassProperty (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:24483:55)
    at _class.pushClassProperty (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:19683:30)
    at _class.parseClassMemberWithIsStatic (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:19616:14)
    at _class.parseClassMemberWithIsStatic (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:24389:58)
    at _class.parseClassMember (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:19553:10)
    at _class.parseClassMember (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:24346:46)
    at _class.parseClassBody (/Users/bkarumuri/.config/yarn/global/node_modules/js2flowchart/dist/js2flowchart.js:19508:12)
```

**Comment by KBPratap** [comment]
installed babel plugin and configured. 
https://babeljs.io/docs/en/babel-plugin-proposal-class-properties
But the issue is not resolved

**Comment by Bogdan-Lyashenko** [comment]
@KBPratap `classProperties ` plugin needed by `babel/parser` I use to build AST (https://babeljs.io/docs/en/babel-parser#plugins), I just added it and published new version. Please try js2flowchart@1.2.0, should be fine now. Thanks.

**Comment by KBPratap** [comment]
```
$ npm install js2flowchart@1.2.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for js2flowchart@1.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<user>/.npm/_logs/2019-07-25T19_27_52_727Z-debug.log
```

**Comment by Bogdan-Lyashenko** [comment]
Can you just try to run `npm i js2flowchart` instead

**Comment by KBPratap** [comment]
finally am able to run it. Thanks for the quick update!

One more thing I noticed:
The install fails with node v10 version so downgraded to node v8 and it worked.
